# Generated by Django 4.1.3 on 2023-01-13 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('preferred_position', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender'), ('goalkeeper', 'Goalkeeper')], max_length=32)),
                ('skill', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stamina_left', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matches_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_scored', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('assists_made', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('loses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('goalkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goalkeeper', to='futsal_sim.player')),
                ('left_attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_attacker', to='futsal_sim.player')),
                ('left_defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_defender', to='futsal_sim.player')),
                ('right_attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_attacker', to='futsal_sim.player')),
                ('right_defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_defender', to='futsal_sim.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futsal_sim.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='futsal_sim.team'),
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cpu_team_name', models.CharField(max_length=128)),
                ('player_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cpu_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cpu_average_skill', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='futsal_sim.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(('preferred_position__in', ['attacker', 'defender', 'goalkeeper'])), name='futsal_sim_player_preferred_position_valid'),
        ),
    ]
