# Generated by Django 4.1.3 on 2023-01-19 21:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futsal_sim', '0002_remove_matchresult_cpu_average_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='cpu_score',
            new_name='cpu_goals',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='player_score',
            new_name='player_goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stamina_left',
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlayerMatchMoment',
        ),
        migrations.AddField(
            model_name='matchgoal',
            name='assister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_moments', to='futsal_sim.player'),
        ),
        migrations.AddField(
            model_name='matchgoal',
            name='goal_scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_moments', to='futsal_sim.player'),
        ),
        migrations.AddField(
            model_name='matchgoal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_moments', to='futsal_sim.matchresult'),
        ),
    ]
