# Generated by Django 4.1.3 on 2023-01-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_sim', '0003_matchgoal_rename_cpu_score_matchresult_cpu_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='coin_reward',
            new_name='coins_reward',
        ),
    ]
