# Generated by Django 4.1.3 on 2023-01-20 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_sim', '0004_rename_coin_reward_matchresult_coins_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='futsal_sim.team')),
                ('skill', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            bases=('futsal_sim.team',),
        ),
        migrations.AlterModelOptions(
            name='matchgoal',
            options={'ordering': ['minute']},
        ),
        migrations.AlterField(
            model_name='matchgoal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_moments', to='futsal_sim.matchresult'),
        )
    ]
