# Generated by Django 4.1.3 on 2023-02-04 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_sim', '0005_cputeam_alter_matchgoal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stamina_left',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
